"""Reproducible service-fixture generator; do not edit this file."""
import json
from pathlib import Path


def render(source, name):
    service = next(row for row in source["services"] if row["name"] == name)
    fixture = {"schema_version": source["schema_version"],
               "service": service["name"], "port": service["port"]}
    return json.dumps(fixture, sort_keys=True, indent=2) + "\n"


def main():
    source = json.loads(Path("source.json").read_text(encoding="utf-8"))
    for name in ("api", "worker"):
        Path("fixtures", f"{name}.json").write_text(
            render(source, name), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
