#!/usr/bin/env python3
"""Assemble dist/ from src/: the installable bundle a consumer project copies in.

Responsible for: producing a fixed, versioned artefact so that dogfooding
tests a known bundle rather than whatever is half-edited in src/. Runs the
harness first and refuses to build on a failure, which is the charter's
"nothing ships out of dist/ until the harness passes".

Deliberately does not: install anything, touch src/, or offer a way past
the harness. If the harness is wrong, fix the harness.

The one non-obvious thing: the version stamp names the source commit the
bundle was built from, which is one commit before the commit that adds
dist/. That is the correct provenance; the bundle cannot know its own
commit. A dirty working tree is stamped "-dirty" and should not be
dogfooded.

Usage:
    python3 tools/build_dist.py              build
    python3 tools/build_dist.py --dry-run    list what would be written
"""
from __future__ import annotations

import argparse
import datetime as dt
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
DIST = REPO_ROOT / "dist"
HARNESS = REPO_ROOT / "test" / "harness" / "check.py"

ORCHESTRATOR_HEADER = """\
# Orchestrator instructions

Bundle version: {version}. Generated by tools/build_dist.py from src/ROUTING.md
and src/LIFECYCLE.md. Append this file to the consumer project's CLAUDE.md, or
keep it beside CLAUDE.md and add the line "Read ORCHESTRATOR.md before
delegating any task." Do not edit here; edit the source and rebuild.

"""


def version_stamp() -> str:
    rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, cwd=REPO_ROOT).stdout.strip() or "no-git"
    dirty = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True, cwd=REPO_ROOT).stdout.strip()
    return f"{dt.date.today().isoformat()}-{rev}{'-dirty' if dirty else ''}"


def planned_files(version: str) -> dict[Path, str]:
    """Map each dist path to its content. Pure; nothing is written here."""
    out: dict[Path, str] = {}
    for agent in sorted((SRC / "agents").glob("WORKER_*.md")):
        out[DIST / ".claude" / "agents" / agent.name] = agent.read_text(encoding="utf-8")
    out[DIST / ".claude" / "commands" / "workers.md"] = (SRC / "commands" / "workers.md").read_text(encoding="utf-8")
    out[DIST / ".claude" / "ORCHESTRATOR_VERSION"] = version + "\n"
    routing = (SRC / "ROUTING.md").read_text(encoding="utf-8")
    lifecycle = (SRC / "LIFECYCLE.md").read_text(encoding="utf-8")
    out[DIST / "ORCHESTRATOR.md"] = ORCHESTRATOR_HEADER.format(version=version) + routing.rstrip("\n") + "\n\n" + lifecycle
    out[DIST / "README.md"] = (SRC / "README.md").read_text(encoding="utf-8")
    assert len([p for p in out if p.parent.name == "agents"]) == 15, "expected fifteen worker definitions"
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dry-run", action="store_true", help="list what would be written; write nothing")
    args = ap.parse_args(argv)

    harness = subprocess.run([sys.executable, str(HARNESS)], capture_output=True, text=True, cwd=REPO_ROOT)
    if harness.returncode != 0:
        print("refusing to build: harness failed\n" + harness.stdout[-1500:], file=sys.stderr)
        return 1

    version = version_stamp()
    files = planned_files(version)
    if args.dry_run:
        for path in sorted(files):
            print(f"would write {path.relative_to(REPO_ROOT)} ({len(files[path])} chars)")
        print(f"version {version}")
        return 0

    staging = DIST.with_name("dist.tmp")
    if staging.exists():
        shutil.rmtree(staging)
    for path, content in files.items():
        target = staging / path.relative_to(DIST)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
    if DIST.exists():
        shutil.rmtree(DIST)
    staging.rename(DIST)
    for path in sorted(files):
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    print(f"version {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
