#!/usr/bin/env python3
"""Generate the fifteen worker definitions in src/agents/ from two sources.

Responsible for: turning src/WORKER_PERSONA.md (shared persona plus one
optional section per cell) and the routing table in src/ROUTING.md into one
Claude Code subagent definition per cell, with the persona inlined so a
worker needs no file read at startup and no file in the consumer project.

Deliberately does not: decide which cells exist (the matrix below is fixed by
CLAUDE.md), touch dist/, or validate the routing table beyond what it needs
to write a description. The harness (test/harness/check.py) does validation.

The one non-obvious thing: a cell whose model-specific section is empty gets
no cell heading at all, so the worker is told nothing about its own cell.
That keeps the open question in CLAUDE.md (does a worker knowing its effort
level help or hurt) answerable by filling sections in, without a code change.

Usage:
    python3 tools/generate_workers.py            write files, report each
    python3 tools/generate_workers.py --check    exit 1 if any file would change
    python3 tools/generate_workers.py --json     machine-readable report
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# tools/ is put on sys.path so `cells` resolves regardless of how this file is
# invoked: as a script, or loaded via importlib.util as check.py does.
sys.path.insert(0, str(REPO_ROOT / "tools"))
from cells import MODELS, EFFORTS  # noqa: E402 (path must be set first)

PERSONA_PATH = REPO_ROOT / "src" / "WORKER_PERSONA.md"
ROUTING_PATH = REPO_ROOT / "src" / "ROUTING.md"
AGENTS_DIR = REPO_ROOT / "src" / "agents"

GENERATED_MARKER = (
    "<!-- GENERATED by tools/generate_workers.py from src/WORKER_PERSONA.md "
    "and src/ROUTING.md. Do not edit by hand. -->"
)
MAX_DESCRIPTION_CHARS = 200


def worker_name(model: str, effort: str) -> str:
    return f"worker-{model}-{effort}"


def file_name(model: str, effort: str) -> str:
    return f"WORKER_{model}_{effort}.md"


def split_persona(text: str) -> tuple[str, dict[str, str]]:
    """Return (general_body, {cell_name: section_body}) from WORKER_PERSONA.md.

    The general body is everything after the "## General worker persona"
    heading up to the first "## model-specific-" heading. Each cell section
    is the text under its heading up to the next "## " heading. Bodies are
    stripped of surrounding blank lines; an empty body means "omit".
    """
    assert "## General worker persona" in text, f"{PERSONA_PATH}: general heading missing"
    lines = text.splitlines()
    general: list[str] = []
    sections: dict[str, list[str]] = {}
    current: str | None = None  # None = before general; "" = general; else cell
    for line in lines:
        if line.startswith("## "):
            title = line[3:].strip()
            if title == "General worker persona":
                current = ""
            elif title.startswith("model-specific-"):
                current = title[len("model-specific-"):]
                sections[current] = []
            else:
                current = None
            continue
        if current == "":
            general.append(line)
        elif current:
            sections[current].append(line)
    general_body = "\n".join(general).strip("\n")
    assert general_body, f"{PERSONA_PATH}: general section is empty"
    return general_body, {k: "\n".join(v).strip("\n") for k, v in sections.items()}


ROW_RE = re.compile(r"^\|\s*(?P<assessment>[^|]+?)\s*\|\s*(?P<worker>[^|]+?)\s*\|\s*$")
NAME_RE = re.compile(r"`(worker-[a-z]+-[a-z]+)`")


def routing_assessments(text: str) -> dict[str, list[str]]:
    """Map each worker name in the ROUTING.md table to the assessments naming it."""
    out: dict[str, list[str]] = {}
    in_table = False
    for line in text.splitlines():
        if line.startswith("| Assessment"):
            in_table = True
            continue
        if in_table and line.startswith("| :---"):
            continue
        if in_table and not line.startswith("|"):
            break
        if not in_table:
            continue
        m = ROW_RE.match(line)
        assert m, f"{ROUTING_PATH}: unparseable table row: {line!r}"
        for name in NAME_RE.findall(m.group("worker")):
            out.setdefault(name, []).append(m.group("assessment"))
    assert out, f"{ROUTING_PATH}: routing table not found"
    return out


def description(model: str, effort: str, assessments: list[str]) -> str:
    head = f"{model.capitalize()} at {effort} effort."
    if assessments:
        routed = "; ".join(a[0].lower() + a[1:] for a in assessments)
        body = f"Routed for: {routed}."
    else:
        body = "Not in the routing table; use only on a documented escalation (ROUTING.md section 2)."
    tail = "Select by subagent_type only; never pass a model parameter."
    text = f"{head} {body} {tail}"
    assert len(text) <= MAX_DESCRIPTION_CHARS, f"{worker_name(model, effort)}: description {len(text)} chars"
    return text


def render(model: str, effort: str, general: str, cell_section: str, assessments: list[str]) -> str:
    parts = [
        "---",
        f"name: {worker_name(model, effort)}",
        f"description: {description(model, effort, assessments)}",
        f"model: {model}",
        f"effort: {effort}",
        "---",
        GENERATED_MARKER,
        "",
        general,
    ]
    if cell_section:
        parts += ["", f"## Cell guidance ({model}, {effort})", "", cell_section]
    return "\n".join(parts) + "\n"


def write_atomic(path: Path, content: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=path.name, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="report drift; write nothing; exit 1 on drift")
    ap.add_argument("--json", action="store_true", help="machine-readable report")
    args = ap.parse_args(argv)

    general, sections = split_persona(PERSONA_PATH.read_text(encoding="utf-8"))
    routed = routing_assessments(ROUTING_PATH.read_text(encoding="utf-8"))
    expected_cells = {f"{m}-{e}" for m in MODELS for e in EFFORTS}
    unknown = set(sections) - expected_cells
    assert not unknown, f"{PERSONA_PATH}: sections for cells outside the matrix: {sorted(unknown)}"
    unknown_routed = set(routed) - {worker_name(m, e) for m in MODELS for e in EFFORTS}
    assert not unknown_routed, f"{ROUTING_PATH}: table names workers outside the matrix: {sorted(unknown_routed)}"

    AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    report: list[dict[str, str]] = []
    drift = 0
    for model in MODELS:
        for effort in EFFORTS:
            name = worker_name(model, effort)
            content = render(model, effort, general, sections.get(f"{model}-{effort}", ""), routed.get(name, []))
            path = AGENTS_DIR / file_name(model, effort)
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing == content:
                status = "unchanged"
            elif args.check:
                status = "differs" if existing is not None else "missing"
                drift += 1
            else:
                write_atomic(path, content)
                status = "wrote"
            report.append({"file": str(path.relative_to(REPO_ROOT)), "status": status})

    if args.json:
        print(json.dumps({"drift": drift, "files": report}, indent=2))
    else:
        for row in report:
            print(f"{row['status']:>9}  {row['file']}")
        print(f"{len(report)} definitions, {drift} drifted")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
